### ISSUE TITLE
How do I use it in Windows JScript?

### ISSUE THREAD

**Issue by laoqiuqiu** [fzcooo/wscript-extra#1]

**Comment by fzcooo** [comment]
抱歉！回复晚了，没留意看issues。
有两种使用方式。
#### 1.如果PC上安装了node. js
把自己写的js文件直接拖拽到build.bat或build.mini.bat上就可以编译，
编译出来的是bat文件，可以直接双击运行。
你可以试试先写一个有以下内容的test1.js

> console.log(process.env);

然后把test1.js拖拽到build.bat上，生成test1.bat文件，双击这个文件会输出环境变量。
脚本里可以使用rollup的import，export。

> import * as _ from 'tool'         //  lib目录下的模块可以直接import，不用指定路径
> import * as fs from './lib/fs'    //  当然指定路径也可以
> import { resolve } from 'path'
> import test2 from './test2'      //  自己写的模块必须指定路径

#### 2.如果PC没装node.js
可以用runtime.bat（最近刚上传）来运行脚本，运行方式是把自己的js文件拖拽到runtime.bat，
或者用cmd命令
> /路径/runtime.bat test.js

runtime.bat是把runtime.js通过上面的方法编译出来的，里面包含了lib目录下大部分模块。
具体包含了那些模块可以看runtime.js的代码。
例子：
test2.js

> import _ from 'chain';
> `_.range(65, 65 + 26).filter(it => it % 6 == 0).map(_.chr).log();`

把test2.js拖拽到runtime.bat上会运行输出
> [ 'B', 'H', 'N', 'T', 'Z' ]
需要注意的是第2种方式只能import内部模块，也就是runtime.js中已经引用的
那些模块，并且不支持export。

两种方式最大的区别是第一种需要先编译后执行，第二种直接执行。

**Comment by fzcooo** [comment]
因为是用的IE11的js引擎执行的，所以IE11中支持的东西在wscript-extra中基本上都支持，
唯一不支持的是异步，其实本来是支持promise的，但是觉得用处不大就去掉了。
很多基础API都跟nodejs类似，性能也跟nodejs比较接近。
